services:
  financial-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/dev.db
      - NEXTAUTH_URL=http://localhost:3000
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env
    volumes:
      - dashboard_data:/app/data
      - dashboard_logs:/app/logs
      - dashboard_backups:/app/backups
    user: "1001:1001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - dashboard-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  dashboard-network:
    driver: bridge

volumes:
  dashboard_data:
    driver: local
  dashboard_logs:
    driver: local
  dashboard_backups:
    driver: local 